services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    command: ["postgres", "-c", "ssl=off"]
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: